
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { ThemeProvider } from "@/components/theme-provider";
import ShoppingCartModel from "@/components/ShoppingCartModel";
import ShoppingCartProvider from "@/components/Providers";
import Footer from "@/components/Footer";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DzComerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}  >
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <ShoppingCartProvider>
            
        <NavBar/>
       <ShoppingCartModel/>

       <div className="pb-6 mt-32 sm:pb-8 lg:pb-12">
        {children}
      
        <Footer/>
       </div>
        </ShoppingCartProvider>
        
        </ThemeProvider>
        </body>
    </html>
  );
}
